import { parseExpression, type SExpression, PAREN, formatS } from './parser';
import { Lexer } from './lexer'

/* NEW VERSION FOR SExpression EXPRESSIONS (N-ARY TREE) */
// Generated by Gemini. Dont understand how it works

const RADIUS = 25; // Node size

export class TreeNode {
  value: string;
  x: number | null = null;
  y: number | null = null;
  children: TreeNode[] = [];

  constructor(value: string) {
    this.value = value;
  }

  isLeaf(): boolean {
    return this.children.length === 0;
  }

  /**
   * Universal Edge Drawer
   * Uses geometry vectors to connect circle-to-circle regardless of angle!
   */
  drawEdge(context: CanvasRenderingContext2D, child: TreeNode) {
    if (this.x === null || this.y === null || child.x === null || child.y === null) return;

    // 1. Calculate the distance and direction vectors between parent and child
    const dx = child.x - this.x;
    const dy = child.y - this.y;
    const distance = Math.sqrt(dx * dx + dy * dy);

    if (distance === 0) return; // Prevent division by zero

    // 2. Unit vector components (direction coefficients)
    const cosTheta = dx / distance;
    const sinTheta = dy / distance;

    // 3. Shift start and end points onto the outer shell of the circles using the radius
    const startX = this.x + RADIUS * cosTheta;
    const startY = this.y + RADIUS * sinTheta;
    const endX = child.x - RADIUS * cosTheta;
    const endY = child.y - RADIUS * sinTheta;

    // 4. Draw the precise edge
    context.strokeStyle = 'gray';
    context.lineWidth = 1.5;
    context.beginPath();
    context.moveTo(startX, startY);
    context.lineTo(endX, endY);
    context.stroke();
  }

  drawNode(context: CanvasRenderingContext2D) {
    if (this.x === null || this.y === null) return;

    context.beginPath();
    context.arc(this.x, this.y, RADIUS, 0, Math.PI * 2, false);
    context.fillStyle = 'white';
    context.fill();
    context.strokeStyle = '#212121';
    context.lineWidth = 1;
    context.stroke();

    context.font = '24px Times New Roman';
    context.textAlign = 'center';
    context.textBaseline = 'middle';
    context.fillStyle = "#212121";
    context.fillText(this.value, this.x, this.y);
  }
}

export function convertSToTree(sNode: SExpression): TreeNode {
  if (sNode.type === 'Atom') {
    return new TreeNode(sNode.value);
  } 
  // It's a Cons node (operator branch)
  const treenode = new TreeNode(sNode.value);
  
  // Recursively convert all children inside the 'rest' array
  treenode.children = sNode.rest.map(convertSToTree);
  
  return treenode;
}

// Canonicalize expression by flattening consecutive left '+'s
export function canonicalize(sNode: SExpression): SExpression {
    if (sNode.type === 'Atom' || sNode.rest.length === 0){
        return sNode;   // Don't change if Atom
    }
    let op = sNode.value;
    // Discard right PAREN () if any
    if (sNode.type === 'Cons' && sNode.rest.length > 1) {
        const rightChild = sNode.rest[1];
        if (rightChild.type === 'Cons' && rightChild.value === PAREN) {
            sNode.rest[1] = rightChild.rest[0];
        }
    }
    //console.log("snode", formatS(sNode))
    //console.log("left", formatS(sNode.rest[0]), ", right:", formatS(sNode.rest[1]))
    let processedLeft = canonicalize(sNode.rest[0]);
    // If unary operator then no right so return already
    if (sNode.rest[1] === undefined){
      // Discard left PAREN () if any
        if (processedLeft.type === 'Cons' && processedLeft.value === PAREN){
            processedLeft = processedLeft.rest[0]
        }
        return { type: 'Cons', value: op, rest: [processedLeft] };
    }
    let processedRight = canonicalize(sNode.rest[1]);

    // Cononicalize (- A B) into (+ A (-B))
    if (op === '-'){
        sNode = {
            type: 'Cons',
            value: '+',
            rest: [ processedLeft, { type: 'Cons', value: '-', rest: [ processedRight! ]} ]
        };
        processedRight = sNode.rest[1];
    } else if (op === '/'){  // Cononicalize (/ A B) into (* A (inv B))
        sNode = {
            type: 'Cons',
            value: '*',
            rest: [ processedLeft, { type: 'Cons', value: 'inv', rest: [  processedRight! ]} ]
        };
        processedRight = sNode.rest[1];
    }  
    op = sNode.value;   // Update op as sNode is updated

    // Flatten (+ (+ A B) C) => (+ A B C)
    if ((op === '+') && processedLeft.type === 'Cons' && processedLeft.value === '+') {
        const result = {
            type: 'Cons',
            value: op,
            rest: [...processedLeft.rest, processedRight! ] } satisfies SExpression;
        return result;
    } else if ((op === '*') && processedLeft.type === 'Cons' && processedLeft.value === '*') {
        return {
            type: 'Cons',
            value: op,
            rest: [...processedLeft.rest, processedRight! ] } ;
    }
    // Discard left PAREN () if any
    if (processedLeft.type === 'Cons' && processedLeft.value === PAREN){
        processedLeft = processedLeft.rest[0]
    }
    
    // Don't change for other operators
    console.log("Natural return")


    return {
        type: 'Cons',
        value: op,
        rest: [ processedLeft, processedRight ]
    };
}


const LEVEL_HEIGHT = 80; // Vertical distance between parent and child lines
const LEAF_SPACING = 60; // Horizontal distance between neighboring leaf nodes

export function calculateTreeLayout(root: TreeNode, canvasWidth: number, startTopOffset = 60) {
  let currentX = 60; // Tracks global horizontal placement

  function traverse(node: TreeNode, depth: number) {
    // 1. Set the Y coordinate based on how deep the node is in the tree
    node.y = depth * LEVEL_HEIGHT + startTopOffset;

    // 2. Base Case: If it's a leaf node, give it the next   available X slot
    if (node.isLeaf()) {
      node.x = currentX;
      currentX += LEAF_SPACING; // Move the anchor right for the next leaf
      return; 
    } 
    // 3. Recursive Case: Layout all children first, then center the parent
    else {
      for (const child of node.children) {
        traverse(child, depth + 1);
      }
      // Center this parent perfectly between its first and last child
      const firstChildX = node.children[0].x!;
      const lastChildX = node.children[node.children.length - 1].x!;
      node.x = (firstChildX + lastChildX) / 2;
    }
  }

  traverse(root, 0);

  let minX = Infinity;
  let maxX = -Infinity;

  function findBounds(node: TreeNode) {
    if (node.x !== null) {
      minX = Math.min(minX, node.x);
      maxX = Math.max(maxX, node.x);
    }
    for (const child of node.children) {
      findBounds(child);
    }
  }

  function shift(node: TreeNode, offsetX: number) {
    if (node.x !== null) {
      node.x += offsetX;
    }
    for (const child of node.children) {
      shift(child, offsetX);
    }
  }

  findBounds(root);
  const treeCenter = (minX + maxX) / 2;
  const offsetX = canvasWidth / 2 - treeCenter;
  shift(root, offsetX);
}



export function drawTree(context: CanvasRenderingContext2D, node: TreeNode) {
  // 1. Pass down through the branches to draw lines and child nodes
  for (const child of node.children) {
    node.drawEdge(context, child); // Draws line from this parent to this child
    drawTree(context, child);      // Recursive call to process deeper branches
  }

  // 2. Draw the current node circle and text on top of the lines
  node.drawNode(context);
}

export function renderPipeline(rawInput: string, ctx: CanvasRenderingContext2D, isCanonicalize: boolean = false) {
  // Clear the canvas window for a fresh frame
  ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height);

  // 1. Parse the string into an SExpression-Expression Tree
  // e.g., Outputs: { type: 'Cons', head: '+', rest: [...] }
  let sExpression= parseExpression(new Lexer(rawInput), 0);
  if (isCanonicalize){
    sExpression = canonicalize(sExpression);
  }

  // 2. Convert pure data nodes into drawable layout nodes
  const visualRoot = convertSToTree(sExpression);

  // 3. Mutate the visual tree to append all x and y positions
  calculateTreeLayout(visualRoot, ctx.canvas.width, 60);

  // 4. Fire the paint loops onto the canvas context
  drawTree(ctx, visualRoot);
}