import { type SExpression, formatS } from './parser';
import { Zipper } from './zipper';
import { displayNum } from './cursor';

/* NEW VERSION FOR SExpression EXPRESSIONS (N-ARY TREE) */
// Generated by Gemini. Dont understand how it works

const RADIUS = 25; // Node size

export class TreeNode {
  value: string;
  x: number | null = null;
  y: number | null = null;
  children: TreeNode[] = [];
  cursorAt: boolean = false;
  cursorSelected: boolean = false;

  constructor(value: string) {
    this.value = value;
  }

  isLeaf(): boolean {
    return this.children.length === 0;
  }

  /**
   * Universal Edge Drawer
   * Uses geometry vectors to connect circle-to-circle regardless of angle!
   */
  drawEdge(context: CanvasRenderingContext2D, child: TreeNode) {
    if (this.x === null || this.y === null || child.x === null || child.y === null) return;

    // 1. Calculate the distance and direction vectors between parent and child
    const dx = child.x - this.x;
    const dy = child.y - this.y;
    const distance = Math.sqrt(dx * dx + dy * dy);

    if (distance === 0) return; // Prevent division by zero

    // 2. Unit vector components (direction coefficients)
    const cosTheta = dx / distance;
    const sinTheta = dy / distance;

    // 3. Shift start and end points onto the outer shell of the circles using the radius
    const startX = this.x + RADIUS * cosTheta;
    const startY = this.y + RADIUS * sinTheta;
    const endX = child.x - RADIUS * cosTheta;
    const endY = child.y - RADIUS * sinTheta;

    // 4. Draw the precise edge
    context.strokeStyle = 'gray';
    context.lineWidth = 1.5;
    context.beginPath();
    context.moveTo(startX, startY);
    context.lineTo(endX, endY);
    context.stroke();
  }

  drawNode(context: CanvasRenderingContext2D) {
    if (this.x === null || this.y === null) return;

    context.beginPath();
    context.arc(this.x, this.y, RADIUS, 0, Math.PI * 2, false);
    context.fillStyle = 'white';
    if (this.cursorAt) context.fillStyle = '#FFD580'
    if (this.cursorSelected) context.fillStyle = '#accbfc';
    if (this.cursorAt && this.cursorSelected) context.fillStyle = '#b9ebeb';
    context.fill();
    context.strokeStyle = '#212121';
    context.lineWidth = 1;
    context.stroke();

    context.font = '24px Times New Roman';
    context.textAlign = 'center';
    context.textBaseline = 'middle';
    context.fillStyle = "#212121";
    context.fillText(this.value, this.x, this.y);
  }
}

export function convertSToTree(sNode: SExpression, zipper: Zipper): TreeNode {
  // Only display 4 decimal places of a flaot
  const treenode = new TreeNode( displayNum(sNode.value) );
  //console.log("sNode:", formatS(sNode), "\nfocus:", formatS(zipper.focus));
  if (sNode === zipper.focus ) treenode.cursorAt = true;
  if (zipper.selected !== null && sNode === zipper.selected.self ) treenode.cursorSelected = true;
  if (sNode.type === 'Atom') {
    return treenode;
  } 
  // It's a Cons node (operator branch)
  // Recursively convert all children inside the 'rest' array
  treenode.children = sNode.rest.map( (s) => convertSToTree(s, zipper));
  
  return treenode;
}


const LEVEL_HEIGHT = 80; // Vertical distance between parent and child lines
const LEAF_SPACING = 60; // Horizontal distance between neighboring leaf nodes

export function calculateTreeLayout(root: TreeNode, canvasWidth: number, startTopOffset = 60) {
  let currentX = 60; // Tracks global horizontal placement

  function traverse(node: TreeNode, depth: number) {
    // 1. Set the Y coordinate based on how deep the node is in the tree
    node.y = depth * LEVEL_HEIGHT + startTopOffset;

    // 2. Base Case: If it's a leaf node, give it the next   available X slot
    if (node.isLeaf()) {
      node.x = currentX;
      currentX += LEAF_SPACING; // Move the anchor right for the next leaf
      return; 
    } 
    // 3. Recursive Case: Layout all children first, then center the parent
    else {
      for (const child of node.children) {
        traverse(child, depth + 1);
      }
      // Center this parent perfectly between its first and last child
      const firstChildX = node.children[0].x!;
      const lastChildX = node.children[node.children.length - 1].x!;
      node.x = (firstChildX + lastChildX) / 2;
    }
  }

  traverse(root, 0);

  let minX = Infinity;
  let maxX = -Infinity;

  function findBounds(node: TreeNode) {
    if (node.x !== null) {
      minX = Math.min(minX, node.x);
      maxX = Math.max(maxX, node.x);
    }
    for (const child of node.children) {
      findBounds(child);
    }
  }

  function shift(node: TreeNode, offsetX: number) {
    if (node.x !== null) {
      node.x += offsetX;
    }
    for (const child of node.children) {
      shift(child, offsetX);
    }
  }

  findBounds(root);
  const treeCenter = (minX + maxX) / 2;
  const offsetX = canvasWidth / 2 - treeCenter;
  shift(root, offsetX);
}


export function drawTree(context: CanvasRenderingContext2D, node: TreeNode) {
  // 1. Pass down through the branches to draw lines and child nodes
  for (const child of node.children) {
    node.drawEdge(context, child); // Draws line from this parent to this child
    drawTree(context, child);      // Recursive call to process deeper branches
  }

  // 2. Draw the current node circle and text on top of the lines
  node.drawNode(context);
}

